//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Action.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ActionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IActionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ActionParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToken([NotNull] ActionParser.TokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ActionParser.token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToken([NotNull] ActionParser.TokenContext context);
}
