//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Action.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class ActionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACE=1, SINGLELINE_COMMENT=2, MULTILINE_COMMENT=3, TOKEN=4, OPEN_BRACE=5, 
		CLOSE_BRACE=6, SEMICOLON=7, COLON=8, KEYWORD=9, STRING=10, DOUBLE_QUOTED_STRING=11, 
		SINGLE_QUOTED_STRING=12, COORDINATES=13, IDENTIFIER=14, INTEGER=15, NATURAL_NUMBER=16, 
		COLOUR=17;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"NEWLINE", "CHARACTER", "WS", "LETTER", "DIGIT", "ALPHANUM", "HEX", "WHITESPACE", 
		"SINGLELINE_COMMENT", "MULTILINE_COMMENT", "TOKEN", "OPEN_BRACE", "CLOSE_BRACE", 
		"SEMICOLON", "COLON", "KEYWORD", "STRING", "DOUBLE_QUOTED_STRING", "SINGLE_QUOTED_STRING", 
		"COORDINATES", "IDENTIFIER", "INTEGER", "NATURAL_NUMBER", "COLOUR"
	};


	public ActionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ActionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'{'", "'}'", "';'", "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACE", "SINGLELINE_COMMENT", "MULTILINE_COMMENT", "TOKEN", 
		"OPEN_BRACE", "CLOSE_BRACE", "SEMICOLON", "COLON", "KEYWORD", "STRING", 
		"DOUBLE_QUOTED_STRING", "SINGLE_QUOTED_STRING", "COORDINATES", "IDENTIFIER", 
		"INTEGER", "NATURAL_NUMBER", "COLOUR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Action.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ActionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x13', '\xC6', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x5', '\x2', '\x37', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x6', '\t', '\x46', '\n', '\t', '\r', '\t', '\xE', '\t', 'G', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\a', '\n', 'Q', '\n', '\n', '\f', '\n', '\xE', '\n', 'T', 
		'\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', '^', '\n', '\v', 
		'\f', '\v', '\xE', '\v', '\x61', '\v', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x5', '\f', 'r', '\n', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\x86', '\n', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x5', '\x12', '\x8A', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\a', '\x13', '\x8E', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x91', 
		'\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\a', '\x14', '\x97', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x9A', 
		'\v', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', 
		'\a', '\x15', '\xA0', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xA3', 
		'\v', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\xA7', '\n', 
		'\x15', '\f', '\x15', '\xE', '\x15', '\xAA', '\v', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\xB0', '\n', 
		'\x16', '\f', '\x16', '\xE', '\x16', '\xB3', '\v', '\x16', '\x3', '\x17', 
		'\x5', '\x17', '\xB6', '\n', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x18', '\x6', '\x18', '\xBB', '\n', '\x18', '\r', '\x18', '\xE', '\x18', 
		'\xBC', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\a', '_', '\x8F', 
		'\x98', '\xA1', '\xA8', '\x2', '\x1A', '\x3', '\x2', '\x5', '\x2', '\a', 
		'\x2', '\t', '\x2', '\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x3', 
		'\x13', '\x4', '\x15', '\x5', '\x17', '\x6', '\x19', '\a', '\x1B', '\b', 
		'\x1D', '\t', '\x1F', '\n', '!', '\v', '#', '\f', '%', '\r', '\'', '\xE', 
		')', '\xF', '+', '\x10', '-', '\x11', '/', '\x12', '\x31', '\x13', '\x3', 
		'\x2', '\b', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', 
		'\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x32', ';', '\x43', '\\', '\x63', '|', '\x5', '\x2', '\x32', ';', '\x43', 
		'H', '\x63', 'h', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', '\xD5', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x3', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x38', '\x3', '\x2', '\x2', '\x2', '\a', 
		':', '\x3', '\x2', '\x2', '\x2', '\t', '<', '\x3', '\x2', '\x2', '\x2', 
		'\v', '>', '\x3', '\x2', '\x2', '\x2', '\r', '@', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\x42', '\x3', '\x2', '\x2', '\x2', '\x11', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'K', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'Y', '\x3', '\x2', '\x2', '\x2', '\x17', 'q', '\x3', '\x2', '\x2', '\x2', 
		'\x19', 's', '\x3', '\x2', '\x2', '\x2', '\x1B', 'u', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', 'w', '\x3', '\x2', '\x2', '\x2', '\x1F', 'y', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x85', '\x3', '\x2', '\x2', '\x2', '#', '\x89', '\x3', 
		'\x2', '\x2', '\x2', '%', '\x8B', '\x3', '\x2', '\x2', '\x2', '\'', '\x94', 
		'\x3', '\x2', '\x2', '\x2', ')', '\x9D', '\x3', '\x2', '\x2', '\x2', '+', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '-', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '/', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x31', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\a', '\xF', '\x2', '\x2', '\x34', 
		'\x37', '\a', '\f', '\x2', '\x2', '\x35', '\x37', '\a', '\f', '\x2', '\x2', 
		'\x36', '\x33', '\x3', '\x2', '\x2', '\x2', '\x36', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x4', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', 
		'\n', '\x2', '\x2', '\x2', '\x39', '\x6', '\x3', '\x2', '\x2', '\x2', 
		':', ';', '\t', '\x2', '\x2', '\x2', ';', '\b', '\x3', '\x2', '\x2', '\x2', 
		'<', '=', '\t', '\x3', '\x2', '\x2', '=', '\n', '\x3', '\x2', '\x2', '\x2', 
		'>', '?', '\t', '\x4', '\x2', '\x2', '?', '\f', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\t', '\x5', '\x2', '\x2', '\x41', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x43', '\t', '\x6', '\x2', '\x2', '\x43', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x46', '\x5', '\a', '\x4', '\x2', '\x45', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\x3', '\x2', '\x2', 
		'\x2', 'G', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'I', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\b', '\t', 
		'\x2', '\x2', 'J', '\x12', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', 
		'\x31', '\x2', '\x2', 'L', 'M', '\a', '\x31', '\x2', '\x2', 'M', 'R', 
		'\x3', '\x2', '\x2', '\x2', 'N', 'Q', '\x5', '\x5', '\x3', '\x2', 'O', 
		'Q', '\t', '\a', '\x2', '\x2', 'P', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 
		'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 
		'R', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 
		'S', 'U', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\x5', '\x3', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\b', '\n', '\x2', '\x2', 'X', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\a', '\x31', '\x2', '\x2', 'Z', '[', '\a', ',', '\x2', 
		'\x2', '[', '_', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\v', '\x2', '\x2', 
		'\x2', ']', '\\', '\x3', '\x2', '\x2', '\x2', '^', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', 
		'\x2', '\x2', '`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '\x63', '\a', ',', '\x2', '\x2', '\x63', 
		'\x64', '\a', '\x31', '\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\b', '\v', '\x2', '\x2', '\x66', '\x16', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'r', '\x5', '!', '\x11', '\x2', 'h', 'r', '\x5', 
		'+', '\x16', '\x2', 'i', 'r', '\x5', '#', '\x12', '\x2', 'j', 'r', '\x5', 
		')', '\x15', '\x2', 'k', 'r', '\x5', '-', '\x17', '\x2', 'l', 'r', '\x5', 
		'\x31', '\x19', '\x2', 'm', 'r', '\x5', '\x19', '\r', '\x2', 'n', 'r', 
		'\x5', '\x1B', '\xE', '\x2', 'o', 'r', '\x5', '\x1D', '\xF', '\x2', 'p', 
		'r', '\x5', '\x1F', '\x10', '\x2', 'q', 'g', '\x3', '\x2', '\x2', '\x2', 
		'q', 'h', '\x3', '\x2', '\x2', '\x2', 'q', 'i', '\x3', '\x2', '\x2', '\x2', 
		'q', 'j', '\x3', '\x2', '\x2', '\x2', 'q', 'k', '\x3', '\x2', '\x2', '\x2', 
		'q', 'l', '\x3', '\x2', '\x2', '\x2', 'q', 'm', '\x3', '\x2', '\x2', '\x2', 
		'q', 'n', '\x3', '\x2', '\x2', '\x2', 'q', 'o', '\x3', '\x2', '\x2', '\x2', 
		'q', 'p', '\x3', '\x2', '\x2', '\x2', 'r', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '}', '\x2', '\x2', 't', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '\x7F', '\x2', '\x2', 'v', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\a', '=', '\x2', '\x2', 'x', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', 'y', 'z', '\a', '<', '\x2', '\x2', 'z', ' ', '\x3', '\x2', 
		'\x2', '\x2', '{', '|', '\a', 'o', '\x2', '\x2', '|', '}', '\a', '\x63', 
		'\x2', '\x2', '}', '\x86', '\a', 'r', '\x2', '\x2', '~', '\x7F', '\a', 
		'u', '\x2', '\x2', '\x7F', '\x80', '\a', 'g', '\x2', '\x2', '\x80', '\x81', 
		'\a', '\x65', '\x2', '\x2', '\x81', '\x82', '\a', 'v', '\x2', '\x2', '\x82', 
		'\x83', '\a', 'k', '\x2', '\x2', '\x83', '\x84', '\a', 'q', '\x2', '\x2', 
		'\x84', '\x86', '\a', 'p', '\x2', '\x2', '\x85', '{', '\x3', '\x2', '\x2', 
		'\x2', '\x85', '~', '\x3', '\x2', '\x2', '\x2', '\x86', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x8A', '\x5', '%', '\x13', '\x2', '\x88', '\x8A', 
		'\x5', '\'', '\x14', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8F', '\a', '$', '\x2', '\x2', '\x8C', '\x8E', 
		'\x5', '\x5', '\x3', '\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x91', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x92', '\x93', '\a', '$', '\x2', '\x2', '\x93', '&', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x98', '\a', ')', '\x2', '\x2', '\x95', '\x97', '\x5', 
		'\x5', '\x3', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9C', '\a', ')', '\x2', '\x2', '\x9C', '(', '\x3', '\x2', '\x2', '\x2', 
		'\x9D', '\xA1', '\x5', '-', '\x17', '\x2', '\x9E', '\xA0', '\x5', '\a', 
		'\x4', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA8', 
		'\a', '.', '\x2', '\x2', '\xA5', '\xA7', '\x5', '\a', '\x4', '\x2', '\xA6', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x5', '-', '\x17', 
		'\x2', '\xAC', '*', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xB1', '\x5', 
		'\t', '\x5', '\x2', '\xAE', '\xB0', '\x5', '\r', '\a', '\x2', '\xAF', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', ',', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\a', '/', '\x2', 
		'\x2', '\xB5', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB8', '\x5', '/', '\x18', '\x2', '\xB8', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xBB', '\x5', '\v', '\x6', '\x2', '\xBA', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\x30', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', '%', 
		'\x2', '\x2', '\xBF', '\xC0', '\x5', '\xF', '\b', '\x2', '\xC0', '\xC1', 
		'\x5', '\xF', '\b', '\x2', '\xC1', '\xC2', '\x5', '\xF', '\b', '\x2', 
		'\xC2', '\xC3', '\x5', '\xF', '\b', '\x2', '\xC3', '\xC4', '\x5', '\xF', 
		'\b', '\x2', '\xC4', '\xC5', '\x5', '\xF', '\b', '\x2', '\xC5', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\x2', '\x36', 'G', 'P', 'R', '_', 
		'q', '\x85', '\x89', '\x8F', '\x98', '\xA1', '\xA8', '\xB1', '\xB5', '\xBC', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
